// application/client/web/mernapps/src/app/getalltickets/getalltickets.tsx
import React from 'react';
import { AgGridReact } from 'ag-grid-react';
import {Link} from 'react-router-dom';
import {Upload} from "../../shared/shared.service";
import Select from "react-select";
import "./getalltickets.scss";
import  {service}   from './getalltickets.service';

class Getalltickets extends React.Component<any, any> {
    columnDefs: any = [{ headerName: 'name', field: 'name' },{ headerName: 'assigness', field: 'assigness' },{ headerName: 'types', field: 'types' },{ headerName: 'severity', field: 'severity' },{ headerName: 'ticketstauts', field: 'ticketstatus' },];
    gridApi: any;
    gridColumnApi: any;
    test = new service ("");
    constructor(props:any){
    super(props);
    this.onRowSelected = this.onRowSelected.bind(this)
    this.state={
    tickets : {
    name: '',
    assigness: '',
    types: '',
    severity: '',
    ticketstatus: '',
    },
    
    rowData :[]
    } }
    


    handlechange = (e: any) => {
    if(e?.target){
    this.setState({ tickets: { ...this.state.tickets, [e.target.name]: e.target.value } })
    }
    }


    componentDidMount() {
    this.state.tickets.created_by = sessionStorage.getItem('email')||'{}';
    this.GpGetAllValues();
    }
    GpGetAllValues  () {
    this.test.GpGetAllValues().then((data:any) => {
    this.setState({rowData:data.data})
    },
    (error:any) => {
    console.log('Error', error);
    });
    }
    onRowSelected(event:any)
    {
    this.props.history.push({pathname:"/updatedeltickets",state:{id : event.data}})
    }
    onGridReady(params :any)
    {
    this.gridApi = params.api;
        this.gridApi.sizeColumnsToFit();
        this.gridColumnApi = params.columnApi;
    }

    render(){
    return(
    <>
        <h2 className="screen-align">getalltickets</h2>
        <div id="template-iebh" className="gjs-row">
    <div id="template-ie3y" className="gjs-cell"></div>
    <div id="template-imaj" className="gjs-cell">
        <div id="template-it5s" className="gjs-row">
            <div id="template-iui6" className="gjs-cell">
                <div id="template-iueb">List of Ticket Status</div>
                <div id="template-i9ig" onClick={()=>this.GpGetAllValues()}className="ag-theme-material" style={{height: '500px',
                    width: '100%'}} >
                    <AgGridReact columnDefs={this.columnDefs} pagination={true}
                    onGridReady={this.onGridReady} paginationPageSize={5} domLayout={
                    "autoHeight"} animateRows={true}defaultColDef={{sortable: true, filter: true }} rowData={this.state.rowData}
                    rowSelection={ "single"} onRowSelected={this.onRowSelected }></AgGridReact>
                </div>
            </div>
        </div>
    </div>
</div>
    </>
    );
    };
    };

    export default Getalltickets;

// application/client/web/mernapps/src/app/getalltickets/getalltickets.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { GetallticketsService } from './getalltickets.service';
import { Router } from '@angular/router';



    export enum ticketstatus {
        OPEN = 'open',
        CLOSE = 'close',
        INPROGRESS = 'inprogress',
    }


@Component({
  selector: 'app-getalltickets',
  templateUrl: './getalltickets.component.html',
  styleUrls: ['./getalltickets.component.scss'],
})

export class GetallticketsComponent implements OnInit {
    columnDefs: any = [{ headerName: 'name', field: 'name'  },{ headerName: 'assigness', field: 'assigness'  },{ headerName: 'types', field: 'types'  },{ headerName: 'severity', field: 'severity'  },{ headerName: 'ticketstauts', field: 'ticketstatus'  },];
    public tickets:any = {
        created_date: '',
        created_by: '',
        last_modified_by: '',
        last_modified_date: '',
        name: '',
        assigness: '',
        types: '',
        severity: '',
        ticketstatus: '',
    }
    gridApi: any;
 	gridColumnApi: any;
 	rowSelection = 'single';
 	defaultColDef = { editable: false, sortable: true, resizable: true, filter: true };
 	paginationPageSize = 10;
 	rowData: any[] = [];
 	rowIndex: Number = 0;




    constructor (
        private getallticketsService: GetallticketsService,
        private router: Router,
    ) { }

    ngOnInit() {
        this.tickets.created_by = sessionStorage.getItem('email') || ''; 
        


    
    }
    GpGetAllValues() {
        this.getallticketsService.GpGetAllValues().subscribe((data:any) => {
            this.rowData = data;
 	 	console.log(data);
        },
        (error:Error) => {
            console.log('Error', error);
        });
    }
    GpRoute(queryId:any) {
        this.router.navigate(['./updatedeltickets'], { queryParams: { 'id': queryId } })
    }
    onSelectionChanged(event:any) {
        const selectedRows = this.gridApi.getSelectedRows();
 	 	this.GpRoute(selectedRows[0]._id);
    }
    onGridReady(params:any) {
        this.gridApi = params.api;
        this.gridApi.sizeColumnsToFit();
        this.gridColumnApi = params.columnApi;
    }


}
<h2 class="screen-align">Getalltickets</h2>
<div id="template-iebh" class="gjs-row">
    <div id="template-ie3y" class="gjs-cell">
        <img id="template-inf5u" src="https://grapesjs-images.s3.amazonaws.com/grapesjsimages/Group%2053441.png"
        class="" />
    </div>
    <div id="template-imaj" class="gjs-cell">
        <div id="template-it5s" class="gjs-row">
            <div id="template-iui6" class="gjs-cell">
                <div id="template-iueb" class="">List of Ticket Status</div>
                <div name="grid_template-i9ig" id="template-i9ig">
                    <ag-grid-angular #agGrid style="width: 100%; height: 100%;" id="myGrid"
                    class="ag-theme-balham" [columnDefs]="columnDefs" [pagination]="true" [paginationPageSize]="paginationPageSize"
                    [defaultColDef]="defaultColDef" [rowData]="rowData" [rowSelection]="rowSelection"
                    (gridReady)="onGridReady($event)" domLayout='autoHeight' (selectionChanged)="onSelectionChanged($event)"></ag-grid-angular>
                </div>
                <div id="myGrid" class="ag-theme-alpine "></div>
            </div>
        </div>
    </div>
</div>
