// application/client/web/mernapps/src/app/updatedeltickets/updatedeltickets.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { UpdatedelticketsService } from './updatedeltickets.service';
import { ActivatedRoute } from '@angular/router';



    export enum ticketstatus {
        OPEN = 'open',
        CLOSE = 'close',
        INPROGRESS = 'inprogress',
    }


@Component({
  selector: 'app-updatedeltickets',
  templateUrl: './updatedeltickets.component.html',
  styleUrls: ['./updatedeltickets.component.scss'],
})

export class UpdatedelticketsComponent implements OnInit {
    queryId: any;
    severityitemArray: any = [];
    typesitemArray: any = [];
    public tickets:any = {
        created_date: '',
        created_by: '',
        last_modified_by: '',
        last_modified_date: '',
        name: '',
        assigness: '',
        types: '',
        severity: '',
        ticketstatus: '',
    }




    constructor (
        private updatedelticketsService: UpdatedelticketsService,
        private activatedRoute: ActivatedRoute,
    ) { }

    ngOnInit() {
        this.tickets.created_by = sessionStorage.getItem('email') || ''; 
        
            this.activatedRoute.queryParams.subscribe((params:any) => { 
 this.queryId = params['id'];
            });


        this.GpGetEntityById();
    
    }
    GpDelete() {
        this.updatedelticketsService.GpDelete(this.queryId).subscribe((data:any) => {
            this.GpGetEntityById();
        },
        (error:Error) => {
            console.log('Error', error);
        });
    }
    typesGpGetAllValues() {
        this.updatedelticketsService.typesGpGetAllValues().subscribe((data:any) => {
            console.log(data);
 	 	this.typesitemArray = data;
        },
        (error:Error) => {
            console.log('Error', error);
        });
    }
    severityGpGetAllValues() {
        this.updatedelticketsService.severityGpGetAllValues().subscribe((data:any) => {
            console.log(data);
 	 	this.severityitemArray = data;
        },
        (error:Error) => {
            console.log('Error', error);
        });
    }
    GpUpdate() {
        this.updatedelticketsService.GpUpdate(this.tickets).subscribe((data:any) => {
            this.tickets.name = ''
 	 	this.tickets.assigness = ''
 	 	this.tickets.types = ''
 	 	this.tickets.severity = ''
 	 	this.tickets.ticketstatus = ''
        },
        (error:Error) => {
            console.log('Error', error);
        });
    }
    GpGetEntityById() {
        this.updatedelticketsService.GpGetEntityById(this.queryId).subscribe((data:any) => {
            this.tickets = data
        },
        (error:Error) => {
            console.log('Error', error);
        });
    }


}
<h2 class="screen-align">Updatedeltickets</h2>
<div id="template-irxy" class="gjs-row">
    <div id="template-i2kk" class="gjs-cell">
        <div id="template-ik0yd" class="gjs-row">
            <div id="template-itkfv" class="gjs-cell">
                <div id="template-ior8q" class="">Start tracking your Tasks & Issues
                    <br id="template-ioa1d" class="">
                </div>
                <div id="template-iatid" class="">Create new ticket</div>
            </div>
        </div>
    </div>
    <div id="template-ii59b" class="gjs-cell">
        <label id="template-igsdy" class="label ">Name
            <br id="template-igjgl" class="">
        </label>
        <input id="template-i2kt8" [(ngModel)]="tickets.name" [ngModelOptions]="{standalone: true}"
        ngDefaultControl class="input form-control " />
    </div>
    <div id="template-ig2i" class="gjs-cell">
        <label id="template-irzn8" class="label ">Assignees</label>
        <input id="template-i8lxh" [(ngModel)]="tickets.assigness"
        [ngModelOptions]="{standalone: true}" ngDefaultControl class="input form-control "
        />
    </div>
    <div id="template-irvh" class="gjs-cell">
        <label id="template-iprz9" class="label ">Severity</label>
        <div id="template-ityx1" class=""></div>
        <div id="template-ifop6" class=""></div>
        <div id="template-ijbve" class="">
            <ng-select id="template-i01rh" name="dynamicdropdown_template-i01rh" [searchable]="true"
            [virtualScroll]="true" [items]="severityitemArray" bindLabel="name" bindValue="name"
            [(ngModel)]="tickets.severity" [ngModelOptions]="{standalone: true}" ngDefaultControl
            (click)="severityGpGetAllValues()" class="form-control "></ng-select>
        </div>
    </div>
    <div id="template-ijpg" class="gjs-cell">
        <label id="template-iudhl" class="label ">Types</label>
        <div id="template-iijtz" class="">
            <ng-select id="template-i2dil" name="dynamicdropdown_template-i2dil" [searchable]="true"
            [virtualScroll]="true" [items]="typesitemArray" bindLabel="name" bindValue="name"
            [(ngModel)]="tickets.types" [ngModelOptions]="{standalone: true}" ngDefaultControl
            (click)="typesGpGetAllValues()" class="form-control "></ng-select>
        </div>
        <div id="template-iikk9" class=""></div>
        <div id="template-ickkl" class=""></div>
    </div>
    <div id="template-i8fws" class="gjs-cell">
        <label id="template-irkcj" class="label ">Status</label>
        <div id="template-ivn2p" class=""></div>
        <select id="template-i87lt" [(ngModel)]="tickets.ticketstatus" [ngModelOptions]="{standalone: true}"
        ngDefaultControl class="select form-control">
            <option value="" id="template-i3wcw" class="">open</option>
            <option value="" id="template-imlug" class="">close</option>
            <option value="" id="template-ik7e5" class="">inprogress</option>
        </select>
    </div>
    <div id="template-i0hso" class="gjs-cell">
        <div id="template-i68l1" (click)="GpUpdate()" class="button btn btn-primary ">Update</div>
        <div id="template-i29qa" (click)="GpDelete()" class="button btn btn-primary ">Delete</div>
    </div>
</div>

// application/client/web/mernapps/src/app/updatedeltickets/updatedeltickets.tsx
import React from 'react';
import { AgGridReact } from 'ag-grid-react';
import {Link} from 'react-router-dom';
import {Upload} from "../../shared/shared.service";
import Select from "react-select";
import "./updatedeltickets.scss";
import  {service}   from './updatedeltickets.service';

class Updatedeltickets extends React.Component<any, any> {
    queryId: any;
    severityitemArray: any = [];
    typesitemArray: any = [];
    test = new service ("");
    constructor(props:any){
    super(props);
    this.state={
    tickets : {
    name: '',
    assigness: '',
    types: '',
    severity: '',
    ticketstatus: '',
    },
     typesoptions:[],  severityoptions:[], 
    rowData :[]
    } }


    handlechange = (e: any) => {
    if(e?.target){
    this.setState({ tickets: { ...this.state.tickets, [e.target.name]: e.target.value } })
    }
     else if(!e.target) { this.setState({tickets: { ...this.state.tickets, [e.name]: e.value } })}
     else if(!e.target) { this.setState({tickets: { ...this.state.tickets, [e.name]: e.value } })}
    }


    componentDidMount() {
    this.state.tickets.created_by = sessionStorage.getItem('email')||'{}';
    if(this.props.location.state){
 	 	this.queryId = this.props.location.state.id._id;
 	 	this.GpGetEntityById();
 	 	};
    this.entitytypesGpGetAllValues();
    this.entityseverityGpGetAllValues();
    }
    GpDelete  () {
    this.test.GpDelete(this.queryId).then((data:any) => {
    this.GpGetEntityById();
    },
    (error:any) => {
    console.log('Error', error);
    });
    }
    entitytypesGpGetAllValues  () {
    this.test.entitytypesGpGetAllValues().then((data:any) => {
    this.typesitemArray = data.data;
                                                                                        this.setState({typesoptions: this.typesitemArray.map((value: any) => {
                                                                                        return {name:"types",label:value.types,value:value.types}})})
    },
    (error:any) => {
    console.log('Error', error);
    });
    }
    entityseverityGpGetAllValues  () {
    this.test.entityseverityGpGetAllValues().then((data:any) => {
    this.severityitemArray = data.data;
                                                                                        this.setState({severityoptions: this.severityitemArray.map((value: any) => {
                                                                                        return {name:"severity",label:value.severity,value:value.severity}})})
    },
    (error:any) => {
    console.log('Error', error);
    });
    }
    GpUpdate  () {
    this.test.GpUpdate(this.state.tickets).then((data:any) => {
    
    },
    (error:any) => {
    console.log('Error', error);
    });
    }
    GpGetEntityById  () {
    this.test.GpGetEntityById(this.queryId).then((data:any) => {
    this.setState({tickets:data.data})
    },
    (error:any) => {
    console.log('Error', error);
    });
    }

    render(){
    return(
    <>
        <h2 className="screen-align">updatedeltickets</h2>
        <div id="template-irxy" className="gjs-row">
    <div id="template-i2kk" className="gjs-cell">
        <div id="template-ik0yd" className="gjs-row">
            <div id="template-itkfv" className="gjs-cell">
                <div id="template-ior8q">Start tracking your Tasks & Issues
                    <br id="template-ioa1d"></br>
                </div>
                <div id="template-iatid">Create new ticket</div>
            </div>
        </div>
    </div>
    <div id="template-ii59b" className="gjs-cell">
        <label id="template-igsdy" className="label ">Name
            <br id="template-igjgl"></br>
        </label>
        <input id="template-i2kt8" onChange={this.handlechange} name="name" value={this.state.tickets.name}className="input form-control "
        />
    </div>
    <div id="template-ig2i" className="gjs-cell">
        <label id="template-irzn8" className="label ">Assignees</label>
        <input id="template-i8lxh" onChange={this.handlechange}
        name="assigness" value={this.state.tickets.assigness}className="input form-control "
        />
    </div>
    <div id="template-irvh" className="gjs-cell">
        <label id="template-iprz9" className="label ">Severity</label>
    </div>
    <div id="template-ijpg" className="gjs-cell">
        <label id="template-iudhl" className="label ">Types</label>
        <div id="template-iijtz">
            <Select id="template-i2dil" options={this.state.typesoptions} onChange={this.handlechange}
            value={this.state.tickets.types}className="form-control "></Select>
        </div>
    </div>
    <div id="template-i8fws" className="gjs-cell">
        <label id="template-irkcj" className="label ">Status</label>
        <div id="template-ivn2p"></div>
        <select id="template-i87lt" onChange={this.handlechange} name="ticketstatus"
        value={this.state.tickets.ticketstatus}className="select ">
            <option value="" id="template-i3wcw">open</option>
            <option value="" id="template-imlug">close</option>
            <option value="" id="template-ik7e5">inprogress</option>
        </select>
    </div>
    <div id="template-i0hso" className="gjs-cell">
        <button id="template-i68l1" onClick={()=>this.GpUpdate()} className="button btn btn-primary "> Update</button>
        <button
        id="template-i29qa" onClick={()=>this.GpDelete()} className="button btn btn-primary "> Delete</button>
    </div>
</div>
    </>
    );
    };
    };

    export default Updatedeltickets;
